## 1 D



In [8]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4])

In [3]:
print(arr)

[1 2 3 4]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
print(arr.ndim)


1


In [6]:
list=[2,3,5,4]
arr2=np.array(list)

In [7]:
print(arr2)

[2 3 5 4]


## 2 D


In [9]:
arr=np.array([
    [1,2,3],[1,2,3],[1,2,3],
    [2,1,3],[2,1,3],[2,1,3],
    [2,1,3],[2,1,3],[2,3,1]
])

In [10]:
print(arr)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [2 1 3]
 [2 1 3]
 [2 1 3]
 [2 1 3]
 [2 1 3]
 [2 3 1]]


In [11]:
arr=np.array([
    [1,2],[2,1],
    [2,3],[4,5]
])

In [12]:
print(arr)

[[1 2]
 [2 1]
 [2 3]
 [4 5]]


In [13]:
arr.size

8

In [14]:
arr.dtype

dtype('int32')

## 3D

In [15]:
arr3=np.array([
    [[1,2,3],[2,3,4]],
    [[1,2,3],[2,3,4]],
    [[1,2,3],[2,3,4]]
])

In [16]:
print(arr3)

[[[1 2 3]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]]

 [[1 2 3]
  [2 3 4]]]


In [17]:
print(type(arr3))

<class 'numpy.ndarray'>


In [18]:
print(arr3.ndim)

3


In [19]:
print(arr.ndim)

2


In [20]:
arr3.size

18

## shape of an array

In [22]:
print(arr.shape)

(4, 2)


In [23]:
print(arr3.shape)

(3, 2, 3)


## Reshape of an array

In [25]:
arr2=np.array([1,2,3,4,6,5])
arr5=arr2.reshape(2,3)

In [26]:
print(arr5)

[[1 2 3]
 [4 6 5]]


In [29]:
arr6=arr2.reshape(3,2)

In [30]:
print(arr6)

[[1 2]
 [3 4]
 [6 5]]


In [31]:
arr=np.array([1,2,3,4,5,6,7,8])
arr1=arr.reshape(2,2,2)

In [32]:
print(arr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
print(arr6)

[[1 2]
 [3 4]
 [6 5]]


In [35]:
arr7=arr6.reshape(2,1,3)

In [36]:
print(arr7)

[[[1 2 3]]

 [[4 6 5]]]


In [37]:
arr5=arr7.reshape(3,2)
print(arr5)

[[1 2]
 [3 4]
 [6 5]]


In [38]:
arr=arr5.reshape(-1)
print(arr)

[1 2 3 4 6 5]


## data type

In [39]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [41]:
arr.dtype

dtype('int32')

In [42]:
arr=np.array([1.2,2.5,2.5])
print(arr)

[1.2 2.5 2.5]


In [43]:
arr.dtype

dtype('float64')

In [44]:
arr=np.array(["a","b","c"])
arr.dtype

dtype('<U1')

### create an array with specifed data type


In [45]:
arr=np.array([1,2,3,4],dtype=np.int64)
arr.dtype

dtype('int64')

In [47]:
arr=np.array([1,2,3,4],dtype='int64')
arr.dtype

dtype('int64')

### conver data type

In [48]:
arr=np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [50]:
arr=arr.astype('int64')
arr.dtype

dtype('int64')

In [53]:
arr1= arr.astype('float32')
arr1.dtype

dtype('float32')

## creation of an array

In [54]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [59]:
arr=np.zeros((4,2),dtype='int32')
print(arr)

[[0 0]
 [0 0]
 [0 0]
 [0 0]]


In [58]:
arr=np.ones(5,dtype='int32')
print(arr)

[1 1 1 1 1]


In [60]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [61]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [62]:
arr=np.arange(2,11,2)
print(arr)

[ 2  4  6  8 10]


In [64]:
arr=np.linspace(10,20)
print(arr)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [67]:
arr=np.linspace(10,20,10)
print(arr)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [69]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [77]:
arr=np.eye(3,k=1)
print(arr)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [78]:
arr=np.eye(3,k=-1)
print(arr)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [79]:
arr=np.full((4,4),5)
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [80]:
arr=np.full(4,5)
print(arr)

[5 5 5 5]


In [81]:
arr=np.full((3,2,3),5)
print(arr)

[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]]


In [82]:
arr=np.random.randint(0,10,5)
print(arr)

[0 2 8 6 9]


In [84]:
arr=np.random.randint(1,10,(4,3))
print(arr)

[[9 7 7]
 [2 9 3]
 [3 7 5]
 [9 8 1]]


In [88]:
arr=np.random.random((4,3))
print(arr)

[[0.61329003 0.96782964 0.52930113]
 [0.32874562 0.51776993 0.27080257]
 [0.61274185 0.79678727 0.58454637]
 [0.94957501 0.17482383 0.5463372 ]]


In [91]:
arr=np.random.rand(4,3)
print(arr)

[[0.66893845 0.81291454 0.14103984]
 [0.74189046 0.52952049 0.83213987]
 [0.52831622 0.96648911 0.52183419]
 [0.49013612 0.89224763 0.37671459]]


In [92]:
arr=np.random.rand(4)
print(arr)

[0.52138688 0.93839758 0.28738777 0.73838026]


## array indexing

 ### 1 D

In [96]:
arr=np.arange(5,15,2)
print(arr)

[ 5  7  9 11 13]


In [97]:
print(arr[2])

9


In [98]:
print(arr[-2])

11


### 2D

In [107]:
arr=np.arange(8,14)
print(arr)

[ 8  9 10 11 12 13]


In [108]:
arr1=arr.reshape(2,3)
print(arr1)

[[ 8  9 10]
 [11 12 13]]


In [114]:
print(arr1[1,1])

12


In [115]:
print(arr1[1,2])

13


In [116]:
print(arr1[0,2])

10


### 3 D

In [123]:
print(arr)

[ 8  9 10 11 12 13 14 15]


In [118]:
arr2=arr.reshape(2,2,2)
print(arr2)

[[[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [122]:
print(arr2[1,1,0])

14


In [120]:
print(arr2[1,0,])

13


In [125]:
arr=np.arange(20,36)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35]


In [126]:
arr2=arr.reshape(4,4)
print(arr2)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]]


In [127]:
print(arr2[2,1])

29


In [128]:
arr3=np.arange(30,57)
print(arr3)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56]


In [129]:
arr4=arr3.reshape(3,3,3)
print(arr4)

[[[30 31 32]
  [33 34 35]
  [36 37 38]]

 [[39 40 41]
  [42 43 44]
  [45 46 47]]

 [[48 49 50]
  [51 52 53]
  [54 55 56]]]


In [130]:
print(arr4[2,2,0])

54


In [131]:
print(arr4[1,1,1])

43


## Array slicing

### 1D

In [138]:
arr=np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [136]:
print(arr[1:10])

[11 12 13 14 15 16 17 18 19]


In [137]:
print(arr[0:4])

[10 11 12 13]


In [139]:
print(arr[:6])

[10 11 12 13 14 15]


In [140]:
print(arr[6:])

[16 17 18 19]


In [141]:
print(arr[-1])

19


In [147]:
print(arr[-1:-5:-1])

[19 18 17 16]


In [144]:
arr2=np.flip(arr)
print(arr2)

[19 18 17 16 15 14 13 12 11 10]


In [148]:
print(arr[1:6:2])

[11 13 15]


### 2D

In [150]:
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [152]:
arr2=arr.reshape(3,3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [160]:
print(arr2[2,0:3])

[7 8 9]


In [161]:
print(arr2[1,1:3])

[5 6]


In [162]:
print(arr2[1:3,0:3])

[[4 5 6]
 [7 8 9]]


### 3D

In [163]:
arr=np.arange(20,84)
print(arr)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67
 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83]


In [164]:
arr3=arr.reshape(4,4,4)
print(arr3)

[[[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]]

 [[52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]
  [64 65 66 67]]

 [[68 69 70 71]
  [72 73 74 75]
  [76 77 78 79]
  [80 81 82 83]]]


In [166]:
print(arr3[1,0,0:5])

[36 37 38 39]


In [168]:
print(arr3[1:3,:,:])

[[[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]]

 [[52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]
  [64 65 66 67]]]


In [169]:
print(arr3[1:3])

[[[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]]

 [[52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]
  [64 65 66 67]]]


In [171]:
print(arr3[1:3,:1])

[[[36 37 38 39]]

 [[52 53 54 55]]]


In [177]:
print(arr3[1,0])

[36 37 38 39]


In [180]:
print(arr3[1:2,:1])

[[[36 37 38 39]]]
