## new learn 

In [11]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4],dtype='complex')
print(arr)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [4]:
arr.itemsize

16

In [5]:
arr.dtype

dtype('complex128')

In [7]:
arr.imag

array([0., 0., 0., 0.])

In [8]:
arr.real

array([1., 2., 3., 4.])

In [9]:
arr.real=np.array([10,20,30,40])

In [10]:
print(arr)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j]


In [14]:
arr=np.empty((2,3))
print(arr)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23058707e-307 2.22526399e-307 2.05837348e-312]]


In [17]:
arr=np.full_like(arr,10)
print(arr)


[[10. 10. 10.]
 [10. 10. 10.]]


In [19]:
arr=np.full_like(arr,20)
print(arr)

[[20. 20. 20.]
 [20. 20. 20.]]


In [21]:
arr=np.zeros_like(arr)
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


## import a file in jupyter notebook

In [23]:
mark=np.loadtxt('marks',skiprows=1)
print(mark)

[[10. 40.]
 [20. 50.]
 [30. 60.]]


## transpose of metrix

In [24]:
print(mark)

[[10. 40.]
 [20. 50.]
 [30. 60.]]


In [28]:
mark1,mark2=np.loadtxt('marks',skiprows=1,unpack=True)
print(mark1,mark2)

[10. 20. 30.] [40. 50. 60.]


 ## From function

In [30]:
arr=np.fromfunction(lambda i,j : i+j,(2,2),dtype='int32')
print(arr)

[[0 1]
 [1 2]]


In [31]:
arr=np.fromfunction(lambda i,j : i+j,(3,3),dtype='int32')
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### it will print the sum of position value like (0,0),(0,1),(1,2) etc.....

## save and load file

In [36]:
np.save('sample',np.array([0,1,2,3,4,5]))


In [38]:
np.load('sample.npy')

array([0, 1, 2, 3, 4, 5])

## masking

In [40]:
b=arr>2
arr[b]

array([3, 3, 4])

In [41]:
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## operations

In [43]:
arr=np.arange(10,19).reshape(3,3)
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [44]:
arr+2

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [45]:
arr-2

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [46]:
arr*2

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36]])

In [47]:
arr1=np.arange(20,29).reshape(3,3)
print(arr1)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [48]:
arr*arr1

array([[200, 231, 264],
       [299, 336, 375],
       [416, 459, 504]])

In [49]:
arr2=np.dot(arr,arr1)
print(arr2)

[[ 765  798  831]
 [ 972 1014 1056]
 [1179 1230 1281]]


In [50]:
arr==arr1

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [65]:
arr=np.array([1,2,3,0])
arr1=np.array([1,2,6,5])

In [66]:
arr==arr1

array([ True,  True, False, False])

In [67]:
np.logical_or(arr,arr1)

array([ True,  True,  True,  True])

In [68]:
np.logical_and(arr,arr1)

array([ True,  True,  True, False])

In [69]:
np.sin(arr)

array([0.84147098, 0.90929743, 0.14112001, 0.        ])

In [70]:
np.log(arr1)

array([0.        , 0.69314718, 1.79175947, 1.60943791])

In [71]:
np.mean(arr)

1.5

In [72]:
np.median(arr)

1.5

In [73]:
np.std(arr)

1.118033988749895

In [74]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692,  1.        ])

## Reduction

In [86]:
print(arr1)

[1 2 6 5]


In [87]:
np.sum(arr1)

14

In [88]:
arr=np.arange(10,19).reshape(3,3)
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [89]:
np.sum(arr,axis=0)

array([39, 42, 45])

In [92]:
np.sum(arr,axis=1)

array([33, 42, 51])

In [93]:
np.min(arr)

10

In [94]:
np.max(arr)

18

In [95]:
np.min(arr,axis=1)

array([10, 13, 16])

## repeat of an array

In [96]:
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [100]:
np.repeat(arr,2,axis=1)

array([[10, 10, 11, 11, 12, 12],
       [13, 13, 14, 14, 15, 15],
       [16, 16, 17, 17, 18, 18]])

In [101]:
np.repeat(arr,2,axis=0)

array([[10, 11, 12],
       [10, 11, 12],
       [13, 14, 15],
       [13, 14, 15],
       [16, 17, 18],
       [16, 17, 18]])

## expanding and squeezing

In [114]:
arr2=np.zeros((4,1,3),dtype='int32')
print(arr2)

[[[0 0 0]]

 [[0 0 0]]

 [[0 0 0]]

 [[0 0 0]]]


In [115]:
mp=np.squeeze(arr2)
print(mp)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [105]:
arr2.shape

(4, 1, 3)

In [108]:
mp.shape

(4, 3)

In [109]:
print(arr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [110]:
arr.shape

(3, 3)

In [120]:
mr=np.squeeze(arr)

In [112]:
print(mr)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [113]:
mr.shape

(3, 3)

#### squeezing is redues the 1 axis in the array.... like (3,1,2) it will change into like(3,2) if the size = 1 then we can add axis to remove element in array

## expanding

In [127]:
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [134]:
np.expand_dims(arr,axis=1).shape

(3, 1, 3)

In [135]:
np.expand_dims(arr,axis=1)

array([[[0., 0., 0.]],

       [[0., 0., 0.]],

       [[0., 0., 0.]]])

In [136]:
np.expand_dims(arr,axis=2).shape

(3, 3, 1)

In [137]:
np.expand_dims(arr,axis=2)

array([[[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.]]])

## bordcasting

In [138]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [139]:
arr+100


array([101, 102, 103])

In [140]:
a=np.array([[1,2,3],[5,6,7]])
print(a)

[[1 2 3]
 [5 6 7]]


In [141]:
a+100

array([[101, 102, 103],
       [105, 106, 107]])

In [142]:
b=np.array([100,200,300])
print(b)

[100 200 300]


In [143]:
a+b

array([[101, 202, 303],
       [105, 206, 307]])

## copy and view

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
arr1=arr.copy()
print(arr1)

[1 2 3 4]


In [5]:
arr1[0]=20

In [6]:
print(arr,arr1)

[1 2 3 4] [20  2  3  4]


In [7]:
arr[2]=30
print(arr,arr1)

[ 1  2 30  4] [20  2  3  4]


## view

In [10]:
arr=np.arange(6,12).reshape(3,2)
print(arr)

[[ 6  7]
 [ 8  9]
 [10 11]]


In [32]:
arr1=arr.view()
print(arr)
print(arr1)

[[30 30]
 [ 8  9]
 [10 11]]
[[30 30]
 [ 8  9]
 [10 11]]


In [33]:
arr1[0]=30
print(arr)
print(arr1)

[[30 30]
 [ 8  9]
 [10 11]]
[[30 30]
 [ 8  9]
 [10 11]]


In [34]:
print(arr1.base)

[30 30  8  9 10 11]


In [35]:
arr1=arr.copy()

In [36]:
print(arr1.base)

None


## array iterating

In [37]:
arr=np.arange(3,9).reshape(3,2)
print(arr)

[[3 4]
 [5 6]
 [7 8]]


### old

In [38]:
for x in arr:
    for y in x:
        print(y)

3
4
5
6
7
8


### there is funtion in numpy nditer()

In [40]:
for x in np.nditer(arr):
    print(x)

3
4
5
6
7
8


#### enumerater

In [41]:
for x,y in np.ndenumerate(arr):
    print(x,y)

(0, 0) 3
(0, 1) 4
(1, 0) 5
(1, 1) 6
(2, 0) 7
(2, 1) 8


### flat()

In [44]:
for x in arr.flat:
    print(x)

3
4
5
6
7
8


### ravel()

In [45]:
arr.ravel()

array([3, 4, 5, 6, 7, 8])

## numpy joins

### concatenate

In [50]:
arr1=np.array([[1,2],[3,2]])
arr2=np.array([[4,7],[5,6]])
print(arr1)
print(arr2)

[[1 2]
 [3 2]]
[[4 7]
 [5 6]]


In [48]:
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 4 7]
 [3 2 5 6]]


In [52]:
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 2]
 [4 7]
 [5 6]]


### stack

In [57]:
arr=np.stack((arr1,arr2))
print(arr)
arr.ndim

[[[1 2]
  [3 2]]

 [[4 7]
  [5 6]]]


3

### vstack

In [54]:
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2]
 [3 2]
 [4 7]
 [5 6]]


### hstack

In [56]:
arr=np.hstack((arr1,arr2))
print(arr)

[[1 2 4 7]
 [3 2 5 6]]


### dstack

In [59]:
arr=np.dstack((arr1,arr2))
print(arr)
arr.ndim

[[[1 4]
  [2 7]]

 [[3 5]
  [2 6]]]


3

## searching in array

In [60]:
print(arr)

[[[1 4]
  [2 7]]

 [[3 5]
  [2 6]]]


In [66]:
x=np.where(arr==4)
print(x)

(array([0], dtype=int64), array([0], dtype=int64), array([1], dtype=int64))


In [67]:
x=np.where(arr%2==0)
print(x)

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 1, 1], dtype=int64), array([1, 0, 0, 1], dtype=int64))


In [97]:
arr=np.arange(2,10)
print(arr)

[2 3 4 5 6 7 8 9]


In [88]:
m=np.searchsorted(arr,7)

In [103]:
np.searchsorted(arr,7, side='left')


5

In [102]:
arr=np.arange(2,10)
print(arr)
np.searchsorted(arr,7, side='right')


[2 3 4 5 6 7 8 9]


6

In [109]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 6, side='left')
print(x)

0


## splitting

### array_split() and split()

In [110]:
arr=np.array([1,2,3,4,5,6])
arr1=np.array_split(arr,3)
print(arr1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [111]:
arr=np.array([1,2,3,4,5,6])
arr1=np.array_split(arr,4)
print(arr1)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [117]:
arr2=np.split(arr,3)
print(arr2)

[array([1, 2]), array([3, 4]), array([5, 6])]


#### spli() is not allow to adjust the element when the element are less than in sourse array

In [137]:
arr=np.array([[1,2],[3,4],[5,6],[6,8]])
arr1=np.array_split(arr,2,axis=1)
print(arr)
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [6 8]]
[array([[1],
       [3],
       [5],
       [6]]), array([[2],
       [4],
       [6],
       [8]])]


In [141]:
arr=np.array([[1,2],[3,4],[5,6],[6,8]])
arr1=np.array_split(arr,2,axis=0)
print(arr)
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [6 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [6, 8]])]


## hsplit ,vslipt and dsplit()

In [143]:
arr=np.array([[1,2],[3,4],[5,6],[6,8]])
arr1=np.hsplit(arr,2)
print(arr)
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [6 8]]
[array([[1],
       [3],
       [5],
       [6]]), array([[2],
       [4],
       [6],
       [8]])]


In [144]:
arr=np.array([[1,2],[3,4],[5,6],[6,8]])
arr1=np.vsplit(arr,2)
print(arr)
print(arr1)

[[1 2]
 [3 4]
 [5 6]
 [6 8]]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [6, 8]])]


In [146]:
arr=np.array([[[1,2],[3,4]],[[5,6],[6,8]]])
arr1=np.dsplit(arr,2)
print(arr)
print(arr1)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 8]]]
[array([[[1],
        [3]],

       [[5],
        [6]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


## sorting

In [148]:
arr=np.random.randint(1,10,6)
print(arr)

[9 5 7 4 2 5]


In [149]:
print(np.sort(arr))

[2 4 5 5 7 9]


In [151]:
arr=np.array([True,False,True,False,False])
print(arr)

[ True False  True False False]


In [152]:
np.sort(arr)

array([False, False, False,  True,  True])

In [157]:
arr=np.array([[[9,8],[5,4]],[[7,6],[6,8]]])
print(arr)
np.sort(arr)

[[[9 8]
  [5 4]]

 [[7 6]
  [6 8]]]


array([[[8, 9],
        [4, 5]],

       [[6, 7],
        [6, 8]]])

## filttering

In [162]:
arr= np.array([1,5,4,3,6,7])
x=[True,True,False,True,False,True]


In [163]:
arr2=arr[x]
print(arr2)

[1 5 3 7]


### to create filtter array based on condition

In [168]:
arr= np.array([1,5,4,3,6,3])
filter_arr=arr>3
arr2=arr[filter_arr]
print(arr2)
print(filter_arr)

[5 4 6]
[False  True  True False  True False]
